version: "3.9"

services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build:
      context: ./airflow
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/crypto_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags

  flask:
    build:
      context: ./flask
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:

